### ISSUE TITLE
Search Previous Queries

### ISSUE THREAD

**Issue by warrenwallis** [warrenwallis/cs130-project#3]
## Epic
As a user, I want my previous queries saved so that I can continue previous work

## User Stories
- [ ] As a user, I want to be able to scroll through my previous queries and results so that I can continue my work or find previous information
- [ ] As a user, I want to be able to quickly ask the same query so that I don't have to copy, move over to the query page, and then paste
- [ ] As a user, I want to be able to filter queries I've asked and data that was received

**Comment by ArvinDing** [comment]
Finished in this https://github.com/warrenwallis/cs130-project/pull/26
