### ISSUE TITLE
As a user, I want to be able to ask new queries in natural language so that I can find new information in the knowledge base despite not knowing how to write in query language

### ISSUE THREAD

**Issue by warrenwallis** [warrenwallis/cs130-project#6]
## User Story
As a user, I want to be able to ask new queries in natural language so that I can find new information in the knowledge base despite not knowing how to write in query language

## Detailed Description
Create a manager that talks between ChatGPT, the database, and the backend of the web-app

## Acceptance Criteria
- [ ] Given a query, then send to ChatGPT to convert
- [ ] Given an invalid response from ChatGPT, then ask the user to clarify or change their question
- [ ] Given a valid response from ChatGPT, then send query to database
- [ ] Given a response from the database, then accept query and send information to frontend

**Comment by ArvinDing** [comment]
Fixed in this https://github.com/warrenwallis/cs130-project/pull/22
